### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by chunshanzhu** [bus1/dbus-broker#10]
ERROR driver_send_reply @ ../src/driver.c +416: State not recoverable
      driver_method_get_connection_selinux_security_context @ ../src/driver.c +1226
      driver_handle_method @ ../src/driver.c +1554
      driver_dispatch_internal @ ../src/driver.c +1752
      driver_dispatch @ ../src/driver.c +1881
      peer_dispatch @ ../src/peer.c +73
      dispatch_context_dispatch @ ../src/util/dispatch.c +203
      manager_run @ ../src/broker/manager.c +202
test-driver: ../src/broker/test-driver.c:758: test_driver_api: Assertion `r >= 0' failed.
      run @ ../src/broker/main.c +123
      main @ ../src/broker/main.c +136
Exiting due to fatal error: -131

**Comment by teg** [comment]
Thanks for the report!

Could you check if you can still reproduce with my latest fix?

**Comment by chunshanzhu** [comment]
The issues has be fixed,thanks
