### ISSUE TITLE
dbus-broker and tmux issue

### ISSUE THREAD

**Issue by Keruspe** [bus1/dbus-broker#11]
This is more of an inherent issue from systemd, but nonetheless a regression compared to a session running on the dbus-daemon.

I have a terminal emulator called Germinal, which follows gnome guidelines for dbus-activatable gapplications (https://wiki.gnome.org/HowDoI/DBusApplicationLaunching).
Germinal launches tmux as its child, attaching to an existing session or creating a new one.

With dbus-daemon, all the process are listed as children of dbus.service by systemd-cgls.
With dbus-broker, each activated dbus service gets its own unit and systemd-cgls lists tmux as part of dbus-org.gnome.Germinal.service

If for some reason I close my terminal, and launch it again, with dbus-daemon the old tmux session gets attached as it still lives as part of dbus.service, whilst with dbus-broker all the process are killed as part of the service, so I get a new tmux session.

What would be the right way of making that work with dbus-broker correctly?

**Comment by teg** [comment]
Hm, interesting. So basically dbus-daemon leaks any child processes of services it starts itself (which is what you want in the tmux case). Could you try passing RemainAfterExit=true to the call to StartTransientUnit() in the launcher? I haven't tried that, but that should not clean up the processes when the main process exits. What will happen when you then restart the same service I'm not sure of.

**Comment by Keruspe** [comment]
Will try, thanks for the suggestion

**Comment by Keruspe** [comment]
I tried that.
It indeed keeps the tmux around and I can attach to it, but I cannot activate the application anymore. (My guess is that the service is still listed as active, so starting a service with the same name is noop)

**Comment by teg** [comment]
As I feared. Not sure what the right thing to do here would be. We could obviously do as the daemon and just fork our own things, but seems broken to me to not have any control over forked processes.

**Comment by Keruspe** [comment]
Well, the way dbus-broker handles that is clearly better, that's just a corner case worth worrying about as I think gnome-terminal is dbus-activated too now, for example, so users of such applications won't be able to reliably use tmux or equivalent.
Ill keep on digging for a solution.

**Comment by Keruspe** [comment]
Ok, I finally managed to workaround that.
After the RemainAfterExit failure, I tried with KillMode=process. that didn't work either as the old transient unit was kept around and dbus-broker thus couldn't start a new one with the same name.
Shipping a regular systemd unit upstream with KillMode=process so that dbus-broker doesn't create a transient one fixes my problem.
