### ISSUE TITLE
Problem parsing Exec= lines with quotes in dbus service files

### ISSUE THREAD

**Issue by jnsh** [bus1/dbus-broker#144]
While investigating why [certain gnome-shell extension didn't work when using dbus-broker](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/77), I discovered an issue with dbus .service files, where the command in the `Exec=` line contains quotes.

I confirmed the issue using dbus services with the following `Exec=` lines, each of which should send a notification with **TEST** in the notification title when activated. I used `gdbus wait --session --activate <service>` for service activation.

These two work without issue:
```
Exec=/bin/notify-send TEST
```
```
Exec=/bin/env notify-send TEST
```

The following sends the notification, but the quotation marks follow to the notification, i.e. notification title becomes **"TEST"**, while it should still be **TEST** without quotations:
```
Exec=/bin/notify-send "TEST"
```

With this one, the command doesn't seem to execute at all. The behavior appears to be the same with any service, where the `Exec=` line contains a command with space somewhere between the quotation marks. This is also causing the issue with the gnome-shell extension mentioned above:
```
Exec=/bin/sh -c "notify-send TEST"
```

All of the above work as intended when dbus-broker is disabled.
Tested with dbus-broker v13.

**Comment by teg** [comment]
Thanks for the report. I'll look into this.

**Comment by teg** [comment]
I could reproduce, and the above patch fixes the issue for me. Thanks again for the report, must have been a pain to figure out!

**Comment by dvdhrm** [comment]
Thanks a lot for the report! Feel free to open another report with some details on the issues you encounter. I will gladly try it myself and see what I can do!
