### ISSUE TITLE
dont try to log to audit as an unprivileged user (log to journal instead)

### ISSUE THREAD

**Issue by doverride** [bus1/dbus-broker#159]
dbus-broker-14-1.fc29.x86_64

Jul 10 10:39:09 agnus dbus-broker-launch[1513]:       bus_selinux_log @ ../src/util/selinux.c +304
Jul 10 10:39:09 agnus dbus-broker-launch[1513]: ERROR util_audit_log @ ../src/util/audit.c +91: Operation not permitted
Jul 10 10:39:09 agnus dbus-broker[1514]: Can't send to audit system: USER_AVC avc:  received setenforce notice (enforcing=1)
                                          exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?

**Comment by doverride** [comment]
Reference:

https://github.com/bus1/dbus-broker/issues/68

**Comment by dvdhrm** [comment]
Errr, ugh. So we do already skip audit for the user-bus. We only specify `--audit` for the system bus. I assume you did not modify the unit-files?

So either there was an selinux-change that now prevents dbus-broker from writing to the audit-log, or we screwed something up.

@teg, might this be related to running as 'dbus' user now? That change was done 2 releases ago, so I wonder whether it can be related.

**Comment by doverride** [comment]
I just ran a `dnf update` and this started happening

**Comment by doverride** [comment]
```
sys.id:sys.role:dbus.system.subj:s0 dbus  1456  0.0  0.0  24368  3676 ?        S    Jul11   0:04 dbus-broker --log 4 --controller 9 --machine-id 051b101002b74ac2a39b5120c22a7c2b --audit
```

With my limited knowledge I would argue that this process runs as an unprivileged user and it instructed to log to audit. AFAIK unpriv users don't have the capability to log to audit.

I do not believe that this has anything to do with SELinux:

```
Jul 12 12:33:46 agnus at-spi-bus-launcher[29346]: dbus-daemon[29350]: Reloaded configuration
Jul 12 12:33:46 agnus dbus-broker-launch[1451]:       bus_selinux_log @ ../src/util/selinux.c +304
Jul 12 12:33:46 agnus dbus-broker-launch[1451]: ERROR util_audit_log @ ../src/util/audit.c +91: Operation not permitted
Jul 12 12:33:46 agnus dbus-broker[1456]: Can't send to audit system: USER_AVC avc:  received setenforce notice (enforcing=1)
                                          exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?
Jul 12 12:33:46 agnus dbus-daemon[29350]: avc:  received setenforce notice (enforcing=1)
Jul 12 12:33:46 agnus audit: PROCTITLE proctitle=736574656E666F7263650031
Jul 12 12:33:46 agnus audit[29707]: SYSCALL arch=c000003e syscall=1 success=yes exit=1 a0=3 a1=7ffc84baf140 a2=1 a3=0 items=0 ppid=2538 >
Jul 12 12:33:46 agnus audit: MAC_STATUS enforcing=1 old_enforcing=0 auid=9999 ses=2 enabled=1 old-enabled=1 lsm=selinux res=1
Jul 12 12:33:40 agnus dbus-broker-launch[1451]:       bus_selinux_log @ ../src/util/selinux.c +304
Jul 12 12:33:40 agnus dbus-broker-launch[1451]: ERROR util_audit_log @ ../src/util/audit.c +91: Operation not permitted
Jul 12 12:33:40 agnus dbus-broker[1456]: Can't send to audit system: USER_AVC avc:  received setenforce notice (enforcing=0)
                                          exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?
Jul 12 12:33:38 agnus dbus-daemon[29350]: avc:  received setenforce notice (enforcing=0)
```
the above is printed when i run:
setenforce 0
setenforce 1

That means that the second occurrence is happening in permissive mode (ie, selinux is not enforcing there)

**Comment by doverride** [comment]
These i ran:
```
echo (auditallow busctl.subj_type_attribute systemd.system.subj (dbus (all)))" > mytest.cil && semodule -i mytest.cil
busctl get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager LogLevel
s "info"
Jul 12 12:43:58 agnus dbus-broker-launch[1451]:       bus_selinux_log @ ../src/util/selinux.c +304
Jul 12 12:43:58 agnus dbus-broker-launch[1451]: ERROR util_audit_log @ ../src/util/audit.c +91: Operation not permitted
Jul 12 12:43:58 agnus dbus-broker[1456]: Can't send to audit system: USER_AVC avc:  granted  { send_msg } for  scontext=wheel.id:sysadm.role:busctl.sysadm.subj:s0 tcontext=sys.id:sys.role:systemd.system.subj:s0 tclass=dbus
                                          exe="/usr/bin/dbus-broker" sauid=81 hostname=? addr=? terminal=?
ps auxZ -q1456
LABEL                           USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
sys.id:sys.role:dbus.system.subj:s0 dbus  1456  0.0  0.0  24368  3676 ?        S    Jul11   0:04 dbus-broker --log 4 --controller 9 --machine-id 051b101002b74ac2a39b5120c22a7c2b --audit
```

**Comment by doverride** [comment]
But even if you give user "dbus" the capability needed to write to audit, and get that to work, Then there still seems to be an issue in that it logs "USER_AVC" instead of "AVC" because its not running as root.

**Comment by doverride** [comment]
Maybe one should start considering not logging to audit anymore period (not sure what the security people would think of that idea)

**Comment by teg** [comment]
Thanks for the extra info. I am now able to reproduce.

> Maybe one should start considering not logging to audit anymore period (not sure what the security people would think of that idea)

I wish ;)

**Comment by doverride** [comment]
BTW , I *suspect* that there are still SELinux policy issues as well in Fedora, and that I might be able to freeze the whole system by triggering those

Try playing with `udisksctl loop-setup`. I have a feeling that this might trigger a dbus-broker crash (not sure though!)

**Comment by teg** [comment]
There were a couple of issues at play here: we were not correctly passing on CAP_AUDIT_WRITE, and when that happened, we did not gracefully fall back to stderr as intended. Was a bit tricky to reproduce as this is not a codepath that is easily hit (only on SELinux failures), but I got an easy reproducer now and to the best of my understanding fixed all the issues in PR #163.

**Comment by doverride** [comment]
I was wrong about this: "Then there still seems to be an issue in that it logs "USER_AVC" instead of "AVC" because its not running as root.". It should alway's just use USER_AVC.

Looking forward to seeing your fixes in Fedora Rawhide

**Comment by teg** [comment]
> I was wrong about this: "Then there still seems to be an issue in that it logs "USER_AVC" instead of "AVC" because its not running as root.". It should alway's just use USER_AVC.

Yes, sorry, glanced over that part. For posterity, AVC v. USER_AVC distinguishes between kernel and userspace events (we are logging the latter), not between root and non-root.
