### ISSUE TITLE
Regression with switch to c-shquote

### ISSUE THREAD

**Issue by Keruspe** [bus1/dbus-broker#172]
Since the switch to c-shquote, some services are no longer working, namely:

```
Nov 02 19:51:52 Lou dbus-broker-launch[667]: Invalid exec '/usr/x86_64-pc-linux-gnu/libexec/accounts-daemon' in service file '/usr/share/dbus-1/system-services/org.freedesktop.Accounts.service' 
Nov 02 19:51:52 Lou dbus-broker-launch[667]: Invalid exec '/usr/x86_64-pc-linux-gnu/libexec/udisks2/udisksd' in service file '/usr/share/dbus-1/system-services/org.freedesktop.UDisks2.service'  
```

 `Accounts.service` looks like this:

```
[D-BUS Service]
Name=org.freedesktop.Accounts
Exec=/usr/x86_64-pc-linux-gnu/libexec/accounts-daemon
User=root
SystemdService=accounts-daemon.service
```

Which looks really simple and correct. Btw, Isn't dbus-broker supposed to use the SystemdService field in this case? Or does the "malformed" exec line invalidate the whole service?

**Comment by dvdhrm** [comment]
Thanks for the report! This should be fixed in `master`. Right, @teg?

**Comment by teg** [comment]
Correct. Though please reopen if that's not the case.
