### ISSUE TITLE
Please use audit to log SELinux denials

### ISSUE THREAD

**Issue by bigon** [bus1/dbus-broker#18]
Hello,

I was quickly looking at the code and I can see that you are using `avc_has_perm_noaudit()` this means that dbus-broker will not log SELinux denials.

Ideally, everything that is denied by SELinux must be logged using the audit framework. Could you please use the `avc_has_perm()` variant and log to audit?

**Comment by bigon** [comment]
OK so apparently `avc_has_perms()` is already used in the `bus_selinux_check_send()` function, while the `_noaudit()` variant is used in `bus_selinux_check_own()`, any reasons?

But anyway the needed callbacks should be set to log to audit

**Comment by teg** [comment]
Thanks for the report! The _noaudit() was an oversight. We intend to add proper audit support, so leaving this issue open for that.

**Comment by teg** [comment]
This was no merged.
