### ISSUE TITLE
[question] Run dbus-broker without systemd running

### ISSUE THREAD

**Issue by jkonecny12** [bus1/dbus-broker#183]
Hello,

I'm working as the Anaconda (Fedora OS installer) [0] developer. Recently we are migrating Anaconda to a modular system where modules (parts of the installer) will connect to each other and communicate by dbus, this is already implement for most of the modules. We are using dbus [1] and we want to migrate to dbus-broker as other applications in Fedora. In fact we have a beta blocker bug for Fedora 30 which would be solved by this.

The problem is that one of our use-cases is building installation images. Not only, but we also support building these images in a mock [2] environment which is basically container so it doesn't have systemd running.

Could you please tell me if there is a way how to start our own dbus session without involving systemd at all? If it is, could you give me some pointers where to start?

[0]: https://github.com/rhinstaller/anaconda
[1]: https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/dbus/launcher.py#L107
[2]: https://github.com/rpm-software-management/mock/wiki

**Comment by dvdhrm** [comment]
Hey!

The core of dbus-broker (the `dbus-broker` binary) has no external dependencies at all, other than a linux kernel. It is a complete bus implementation according to the dbus specification (see `dbus-broker(1)` man-page).

However, most of the time you expect an environment around a bus that provides many more features atop of the pure bus broker. This is why we also provide `dbus-broker-launch` (see `dbus-broker-launch(1)` man-page). This is a compatibility interface to dbus-daemon, that tries to provide an environment as close to what dbus-daemon provides.
When writing this compatibility launcher, we decided to strip all legacy features and instead built on top of what is present on a modern Fedora system. This means, this implementation requires an activation environment which includes a running systemd manager.

If all you need is a simple bus without any features on top, you can easily run `dbus-broker` directly without any launcher. However, if you need dbus-activation, then you need a bus controller that spawns dbus-services when they are activated. The compatibility launcher uses systemd to do this. If you want to spawn dbus-services without systemd, you need a suitable replacement. I am not aware of any replacement on Fedora, but you can of course roll your own. In this case it is up to you to implement the controller interface documented in `dbus-broker(1)`, spawn the dbus-services, track and monitor them.

What exactly are your requirements? Do you need dbus-activation? Why is there no systemd available? What do you use to spawn the different modules running in anaconda?

Cheers!
David

**Comment by teg** [comment]
If you don't need dbus-activation (and you know you never will), then one option would be to make it possible to opt-out of support for that via a dbus-broker-launch commandline argument. Something like --scope=none. The downside of that is that stuff may use dbus-activation without you being aware (unless you really have a very restricted set of services running).

Another option would be to let your launcher do the dbus-activation just like systemd does by exposing the same API on the bus (this would be StartTransientUnit, SetEnvironment, and possibly StartUnit).

**Comment by jkonecny12** [comment]
Thanks for your answer.

Based on that it looks like the best way for us will be to remove our dbus-activation and just start the modules manually.

Right now we are using dbus-activation, one of the reasons is that addons will just reserve name and we will find them based on the name prefix and start them on DBus. This is a nice functionality but not mandatory one.

To answer your questions:
> What exactly are your requirements?

Our requirement is to split functionality to modules, which can be easily disabled and added and which have a stable API. That was the reason why we chose DBus for the communication between the modules. Modules will communicate with each other the same way as addons so they will use the documented DBus interface.
There will be main process which will role as controller of the processes and other similar things.

If we rewrite our auto-activation feature we have now, we will rewrite parts of this controller, so instead it will spawn the processes by itself. The rewrite will make things little bit more complex but it should work.

> Do you need dbus-activation?

We are using it now but we should be able to rewrite our code to avoid that.

> Why is there no systemd available? 

As I described in the first comment one of the requirement of Anaconda is to be able to run in the mock. The mock tool is used mainly to build packages but release engineering is using this tool to also build images. To build an image you need to use Anaconda.

Mock tool basically works as container / chroot (depends on how you run it). So or so, there is no setup of systemd. We may be able to run it there but all the settings would be our responsibility which we want to avoid. Also there could be a plenty of other problems raised by the fact that no-one testing this use-case.

> What do you use to spawn the different modules running in anaconda?

Right now the controller process will find out the services with known prefix in name and call `StartServiceByName` on them.

**Comment by jkonecny12** [comment]
> If you don't need dbus-activation (and you know you never will), then one option would be to make it possible to opt-out of support for that via a dbus-broker-launch commandline argument. Something like --scope=none. The downside of that is that stuff may use dbus-activation without you being aware (unless you really have a very restricted set of services running).

I think we have this environment. The only services running in our environment should be our modules and our addons. What will be the benefit of running `dbus-broker-launch --scope=none` vs running ` 
dbus-broker`?

Also could you please help me how to pass the controller socket in `dbus-broker-launch`. From my understanding it is working with systemd socket unit activation, do you have an example implementation of how we can avoid using socket there? This looks simpler with `dbus-broker`.

**Comment by teg** [comment]
`dbus-broker-launch --scope=none` still gives you parsing of the policy XML, in case you need that, but otherwise using `dbus-broker` directly would probably be nicer/simpler.

To pass the socket, you could look at how it is done in at-spi2: https://gitlab.gnome.org/GNOME/at-spi2-core/commit/d7f47c99d093ba91eb18523e14b23bde1794f5bc

**Comment by jkonecny12** [comment]
We have [these configuration files](https://github.com/rhinstaller/anaconda/tree/master/data/dbus).

It is session bus config mixed with the system one but I don't know how many changes we need to make dbus-broker usable for our use-case, not sure what defaults are. Also there are configuration files for every module.

**Comment by dvdhrm** [comment]
As discussed at DEVCONF19, the easiest way to get this running is to use a custom launcher with only the bits and pieces you really need.

I will close this now. If anyone is still interested in this, please feel free to reopen a new report!

**Comment by jkonecny12** [comment]
Yes exactly, thanks for all your help!
