### ISSUE TITLE
feature request: modernize access control

### ISSUE THREAD

**Issue by doverride** [bus1/dbus-broker#187]
DBus access control (SELinux extension) is too coarse. There is no distinction between sending and receiving messages, There is also no distinction between sending method calls and signals. DBus is now an important part of the core OS, and so it would be nice to have a look at the possibilities of modernizing SELinux Access control and access control in general.

**Comment by teg** [comment]
I think the kinds of access control that might make sense (without getting as detailed as the dbus policy language, which is way too fine-grained I think) is "own name" (as today), "call method" (only applied to method calls, rather than any outgoing message), and possibly "receive signal". To the extent receive policies are used in dbus today, they are about restricting who can listen to certain signals, and that might make sense (rather than considering all signals "public"). I don't really see the value in restricting who can actually emit signals though...

**Comment by teg** [comment]
That said, I guess discussing the access control should really be done on the DBus reference implementation mailing list (as it may go into the spec?) or upstream SELinux. We would be happy to contribute to the discussion, but we are unlikely to go off and implement anything on our own that doesn't come from DBus/SELinux upstream.

**Comment by doverride** [comment]
> I think the kinds of access control that might make sense (without getting as detailed as the dbus policy language, which is way too fine-grained I think) is "own name" (as today), "call method" (only applied to method calls, rather than any outgoing message)

With any "outgoing message" you are referring to the fact that "call method" currently also applies to "signal"? Are there any other outgoing messages covered by "call method" that are not "method calls"?
(in the scenario where unexpected replies are not supported)

> , and possibly "receive signal".

Why "possibly"? Do you not see the need for this? From a SELinux perspective (as discussed here: https://github.com/SELinuxProject/refpolicy/issues/18) do you appreciate and agree with the concerns raised here?

> To the extent receive policies are used in dbus today, they are about restricting who can listen to certain signals, and that might make sense (rather than considering all signals "public"). I don't really see the value in restricting who can actually emit signals though...

I agree, and yes i suppose this is not the proper channel to do this, but I just wanted to get a sense of things first. See if there is a willingness here to take a fresh look at dbus access control.

You say that access control is currently way to fine grained. What room for improvement do you see here other than what you mentioned above?

**Comment by dvdhrm** [comment]
I will close this report here. There are ongoing discussions on the `dbus` issue-tracker over on gitlab.freedesktop.org. I think the upstream specification and reference implementation are the place to discuss this. We do not intend to provide alternative policy implementations, but will follow the upstream development instead.

If this turns into dbus-broker specific implementation issues, we can always resume the discussion here. Until then, I want to keep the discussion on the issue-tracker of the reference implementation so we get a wider audience and better coordination with the specification.
