### ISSUE TITLE
fedora copr 18 months out of date, no fedora 27 28 29 packages

### ISSUE THREAD

**Issue by mikelpr** [bus1/dbus-broker#196]

**Comment by dvdhrm** [comment]
Can you elaborate a bit on this? `dbus-broker` packages exist in Fedora since F29.

**Comment by dvdhrm** [comment]
All official Fedora packages are listed here: https://apps.fedoraproject.org/packages/dbus-broker

**Comment by mikelpr** [comment]
sorry, I didn't know it was added in f29. but f29's package is version 16 that's why I was reporting it was outdated. anyways I've seen there now that f30 will ship 19, good.

**Comment by dvdhrm** [comment]
No worries. @teg is doing Fedora packaging. I am not entirely sure but I don't think we are allowed to update packages with non-bugfixes. If a Fedora version enters beta, we only backport important bugfixes. The newest broker will always be available in rawhide, though.
