### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [bus1/dbus-broker#20]
I would like to point out that identifiers like “[`_ACTIVATION_E_SUCCESS`](https://github.com/bus1/dbus-broker/blob/bf9e805f0b93160b42f85f480c0b73407ab171f7/src/bus/activation.h#L21 "Update candidate")” and “[`_CONTROLLER_E_SUCCESS`](https://github.com/bus1/dbus-broker/blob/b0e228509096fa320e63eb58dc0f4469741c01b6/src/broker/controller.h#L24 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by dvdhrm** [comment]
I do not believe those are problematic.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by dvdhrm** [comment]
I do not believe those are problematic.

**Comment by dvdhrm** [comment]
I am closing this now. We rely on many things the C standard does not guarantee, but which gcc guarantees to us (and clang as well). Any serious C compiler on linux would provide the same guarantees. The C standard allows very weird stuff, like padding bits in integers, etc. I consider those identifiers to belong into the same groups of "obscureness".

If there is any serious issue with using those identifiers, please elaborate!

**Comment by elfring** [comment]
I would appreciate if you would [care more for the rules from the standard specification of these programming languages](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
How can your software be improved further (also around standard compliance) there?

**Comment by teg** [comment]
As David already said, we rely on gcc/clang behavior, and do not intend to change this unless it causes any real problems.
