### ISSUE TITLE
Newly installed D-Bus services (including applications) require logout to be launchable

### ISSUE THREAD

**Issue by hadess** [bus1/dbus-broker#202]
dbus-broker-20-4.fc30.x86_64

Installing pretty much any modern GNOME application, nearly all of them being D-Bus services as well as applications, will require a logout/login for applications to be launchable via the Shell, the file manager, etc.

1. Install and Fedora 30
2. Login to default GNOME session
3. Install a DBusActivatable GNOME application, such as `dnf install seahorse`
4. Launch "Passwords and Keys" (seahorse) from GNOME Shell's application view -> nothing happens
 Try again to D-Bus activate the application through the command-line:
```sh
$ gapplication launch org.gnome.seahorse.Application
error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```
5. Launching `seahorse` by hand works and registers it on the session bus:
```sh
$ gdbus introspect --session --dest org.gnome.seahorse.Application --object-path /org/gnome/seahorse/Application
node /org/gnome/seahorse/Application {
  interface org.freedesktop.DBus.Properties {
    methods:
...
```

**Comment by dvdhrm** [comment]
Yeah, this is a bug in v20 which I fixed just hours ago. v21 which I also released works correctly again. There is already a bodhi update pending as well.

I hope this fixes all issues! Thanks a lot!
David

https://github.com/bus1/dbus-broker/commit/fa1567a13e50299d91213a0822e59ac24ab20fad
https://bodhi.fedoraproject.org/updates/dbus-broker-21-1.fc30

**Comment by hadess** [comment]
Tested, and it works, thanks!

**Comment by p1u3o** [comment]
I'm still running into this with `dbus-broker-21-6.fc31.x86_64`

```
$ gapplication launch org.gnome.seahorse.Application 
error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
````

```
$ systemctl reload --user dbus-broker.service
$ gapplication launch org.gnome.seahorse.Application
## Seahorse runs.
```

**Comment by hadess** [comment]
> I'm still running into this with `dbus-broker-21-6.fc31.x86_64`

See #211

**Comment by dvdhrm** [comment]
Thanks @hadess. This is indeed a different problem, since a reload fixes it. The initial bug required an actual restart. Let's keep discussion in #211?
