### ISSUE TITLE
Failed to start D-Bus User Message Bus

### ISSUE THREAD

**Issue by bilias** [bus1/dbus-broker#203]
Hi,
I've having trouble after updating to Fedora 30 with dbus-broker and gnome-keyring-daemon
dbus-daemon-1.12.14-1.fc30.x86_64
dbus-broker-21-3.fc30.x86_64

journalctl -b -p err
[logs.txt](https://github.com/bus1/dbus-broker/files/3243839/logs.txt)

There is also a bugzilla for this but no reply so far.
https://bugzilla.redhat.com/show_bug.cgi?id=1711545

If I restart gnome-key-daemon then it's connected and all work normally

journalctl -b|grep gnome-keyring-dae
Jun 01 17:14:26 laura gnome-keyring-daemon[1835]: Gkm: using old keyring directory: /home/bilias/.gnome2/keyrings
Jun 01 17:14:26 laura gnome-keyring-daemon[1835]: Gkm: using old keyring directory: /home/bilias/.gnome2/keyrings
Jun 01 17:14:26 laura gnome-keyring-daemon[1835]: couldn't connect to dbus session bus: Could not connect: Connection refused
Jun 01 17:14:26 laura gnome-keyring-daemon[1835]: couldn't connect to dbus session bus: Could not connect: Connection refused
Jun 01 17:14:45 laura gnome-keyring-daemon[1835]: couldn't connect to dbus session bus: Could not connect: Connection refused
Jun 01 17:14:48 laura gnome-keyring-daemon[2924]: Replacing daemon, using directory: /run/user/1000/keyring
Jun 01 17:14:48 laura gnome-keyring-daemon[2924]: Gkm: using old keyring directory: /home/bilias/.gnome2/keyrings
Jun 01 17:14:48 laura gnome-keyring-daemon[2924]: Gkm: using old keyring directory: /home/bilias/.gnome2/keyrings
Jun 01 17:14:51 laura gnome-keyring-daemon[2924]: asked to register item /org/freedesktop/secrets/collection/login/924, but it's already registered
Jun 01 17:14:51 laura gnome-keyring-daemon[2924]: asked to register item /org/freedesktop/secrets/collection/login/924, but it's already registered

Any help on debugging this? Does it seem like a dbus problem or gnome-keyring?

thanks,
Giannis

**Comment by bilias** [comment]
Problem solved
dbus-broker.service was disabled in --user unit-files

systemctl --user enable dbus-daemon.service

**Comment by dvdhrm** [comment]
That is unexpected. A unit should usually not be disabled by default. This might be a side-effect of the presets, though. Anyway, glad you solved it!
