### ISSUE TITLE
dbus activation is not retired in some failure modes

### ISSUE THREAD

**Issue by marmarek** [bus1/dbus-broker#209]
There are cases when dbus activation is not retried when it failed initially. The one I've found is when service claims to be started successfully, but terminates before claiming the name on the bus (I believe). In such a case `activation->requested` remains set to `true` (verified with gdb) and the service start isn't retried anymore.

A concrete example:
1. Create user session without X server running (`DISPLAY` is not set)
2. Try to use `org.freedesktop.Notifications` API (for example call `notify-send xxx`) - this will request notification daemon in my case `mate-notification-daemon`, which will exit early due to lack of `DISPLAY` variable. `notify-send xxx` will timeout.
3. Start X server, inject `DISPLAY` into service activation environment (for example `systemctl --user import-environment DISPLAY`, if not done automatically)
4. Try to issue notification again - `notify-send xxx` will timeout and various debugging techniques confirms the service wasn't even attempted to be started.

Specific messages from notification daemon:
```
Aug 08 08:47:19 sys-vpn systemd[654]: Created slice dbus\x2d:1.2\x2dorg.freedesktop.Notifications.slice.
Aug 08 08:47:19 sys-vpn systemd[654]: Started dbus-:1.2-org.freedesktop.Notifications@0.service.
Aug 08 08:47:19 sys-vpn mate-notification-daemon[689]: Unable to init server: Could not connect: Connection refused
Aug 08 08:47:19 sys-vpn mate-notificati[689]: cannot open display: 
Aug 08 08:47:19 sys-vpn systemd[654]: dbus-:1.2-org.freedesktop.Notifications@0.service: Succeeded.
```

I believe the same will happen if the systemd service initially has some condition not met (for example `ConditionPathExists=`, that later is met.

By inspecting the source code, I see that `activation->requested = false` is set only when the service is properly started, or failed to start at all (according to systemd). But there is no handling for the apparently successful startup, but service never appearing on the bus.

For transient systemd units (like in this case) timeout handling could be delegated to systemd by setting `Type=dbus` and appropriate `BusName=` (if default would be good). But I think non-transient case should be handled by dbus-broker too.

BTW it worked fine with dbus-daemon.

**Comment by dvdhrm** [comment]
Mhhh. This is unfortunate. Imagine a service activation is requested and the unit is a oneshot-unit that spawns some external service. In this case, we have no idea how long to wait until we consider this activation failed. There is no indication to us whether this activation errored out other than the initial unit returning with an error. Hence, this is what we react on.

What you are saying now is that dbus-daemon consider an activation failed after some time elapsed without the name being claimed? Or does dbus-daemon track the service-state and as soon as the service is no longer live it considers the activation as failed? The latter would clearly break the oneshot-unit use-case.

Anyway, we need to stay compatible with dbus-daemon, so my suggestion would be to have a timeout in dbus-broker that resets "activation->requested" after like 60s or so. What I dislike about this is that we now rely on this timeout for actual operations. The correct thing would be to watch "Stopped" notifications of the units we start, but then again this will break oneshot-units. But maybe that is the correct thing to do?

@teg, do you have other ideas?

**Comment by marmarek** [comment]
I think there is a timeout handling for actual call that triggered the activation - maybe that could be used for resetting `activation->requested` too?

Anyway, I think this particular case is much easier to solve - let systemd monitor whether the service claims the name (`Type=dbus`, specify `BusName`) and let it handle the timeout. Since this unit file is generated by dbus-broker, this should be trivial. Note that it will also consider the service started only after it claims the name, so `dbus-broker` doesn't need to re-implement that logic, at least for this case (but probably needs for other cases).

**Comment by dvdhrm** [comment]
> I think there is a timeout handling for actual call that triggered the activation - maybe that could be used for resetting `activation->requested` too?

The D-Bus protocol has no timeouts. Some client libraries try to provide those, but they are handled purely client-side.

**Comment by dvdhrm** [comment]
> Anyway, I think this particular case is much easier to solve - let systemd monitor whether the service claims the name (`Type=dbus`, specify `BusName`) and let it handle the timeout. Since this unit file is generated by dbus-broker, this should be trivial. Note that it will also consider the service started only after it claims the name, so `dbus-broker` doesn't need to re-implement that logic, at least for this case (but probably needs for other cases).

Thing is, we do not control the unit-file (except for transient units, where I think we already use type 'dbus', @teg ?).

**Comment by marmarek** [comment]
> except for transient units, where I think we already use type 'dbus', @teg ?)

The point is, you don't:
```
$ cat /run/user/1000/systemd/transient/dbus-\:1.2-org.freedesktop.Notifications@1.service 
# This is a transient unit file, created programmatically via the systemd API. Do not edit.
[Service]
ExecStart=
ExecStart=-@/usr/libexec/mate-notification-daemon "/usr/libexec/mate-notification-daemon"
KillMode=process
```

**Comment by teg** [comment]
Hm, interesting issue. Using type=dbus would have been elegant, but there is one non-trivial issue: when the bus is not the user bus (but for instance the accessibility bus), then the systemd instance is unable to monitor the name being registered (the systemd user instance is only aware of names on the user bus).

**Comment by marmarek** [comment]
What about adding `Type=dbus` conditionally (for user and system bus only)? It doesn't solve similar issue for other buses, but it's elegant solution for the common case.

**Comment by ilya-fedin** [comment]
I'm hitting this issue as well. I'm starting weston in X session from time to time to test some things and if some programs wants to send a notification, MATE notification daemon fails to launch and dbus-broker doesn't attempt to start it at all anymore, until I run it manually.

**Comment by dvdhrm** [comment]
Oh dear, I was wrong all along. We do handle errors from `StartUnit()` in the launcher, but this only handles errors until the service is **activated**. It does not wait until it is **active**. I completely got that wrong in the systemd bus API. This is not particularly bad, but it means we do not see errors from failing services, unless they fail early.

I am really sorry about that!

I now merged #250 which extends the launcher to track the `ActiveState` of units. This means, we will now always clear pending activations if the service in question enters a failed state. I hope this fixes most of the situations where we miss failed activations.

Again, sorry about completely missing that. I only ever tested with early unit failure. I now verified that running things like `/bin/false` will also correctly be caught by the launcher.

If I missed something, feel free to re-open! And thanks for all the input on the issue!

**Comment by ilya-fedin** [comment]
I applied your patch to dbus-broker 22 from my distro and it doesn't seem to fix the problem (or my case at least). If I make a request to the notification daemon when weston is running, dbus-broker creates a transient unit and removes it so fast that I can't check status with systemctl, journalctl helps fortunately:
```
янв 20 15:11:26 nixos systemd[933]: Started dbus-:1.3-org.freedesktop.Notifications@3.service.
янв 20 15:11:26 nixos .mate-notificat[2480]: Theme parsing error: gtk-contained.css:2871:228: Missing closing bracket for :not()
янв 20 15:11:27 nixos systemd-coredump[2485]: Process 2480 (.mate-notificat) of user 1000 dumped core.
янв 20 15:11:27 nixos systemd[933]: dbus-:1.3-org.freedesktop.Notifications@3.service: Succeeded.
```

busctl waits for 30s and fails. All subsequent calls to the service failing in 30s with the difference that even no transient unit is being created at all. If I run notification daemon process manually, dbus-broker resumes attempts to start it on subsequent calls.

**Comment by ilya-fedin** [comment]
Maybe it's worth to set `Type=exec` on transient units?

**Comment by ilya-fedin** [comment]
Hmm, it's strange, but transient units have content like this:
```
   systemctl --user cat dbus-:1.3-org.mate.panel.applet.ClockAppletFactory@0.service
# /run/user/1000/systemd/transient/dbus-:1.3-org.mate.panel.applet.ClockAppletFactory@0.service
# This is a transient unit file, created programmatically via the systemd API. Do not edit.
[Service]
ExecStart=
ExecStart=-"/nix/store/c7m74ak5glwfhzj5i2qlxcm92ahp0cj3-mate-panel-1.24.1/libexec/clock-applet"
KillMode=process
```
So, if I'm not mistaken, it will be considered successful regardless of the process exit code?

**Comment by dvdhrm** [comment]
You are right. We incorrectly ignored execution failures in transient units. I just pushed another commit:

    https://github.com/bus1/dbus-broker/commit/4f29fe99b00221c689d7418cef78f86b2aa16331

With this, both transient and normal units are correctly restarted on my machine (I test with `/bin/false`).

**Comment by ilya-fedin** [comment]
I built dbus-broker from the latest commit and the unit goes to failed state... But the bug is still there :(
Looking at session bus with Bustle, no PropertiesChanged signal from systemd is emitted:
![image](https://user-images.githubusercontent.com/17829319/105396177-7d3bb400-5c17-11eb-9c6f-5829b8b90f59.png)

Maybe it works with PID 1 and doesn't work with systemd-user?
```
   systemctl --version
systemd 247 (247)
+PAM +AUDIT -SELINUX +IMA +APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 -ZSTD +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Comment by dvdhrm** [comment]
> Maybe it works with PID 1 and doesn't work with systemd-user?

Apparently systemd does not send any D-Bus signals until someone subscribes by calling `Subscribe()` on its API. Since the other systemd services call this unconditionally, this feature is rather useless (systemd-logind for instance always subscribes). However, on the user bus, there might be systems where no-one calls this.

I now extended dbus-broker to always subscribe, so systemd will send the requested notifications. This feels a bit stupid, but it is what it is.

**Comment by ilya-fedin** [comment]
@dvdhrm thank you, the bug is finally fixed! There's no waiting for timeout anymore, error is returned instantly as the service fails. There's no need to run the service manually to restore it functionality anymore, it restores automatically. The only difference I noticed is that failed transient units aren't being removed:
![image](https://user-images.githubusercontent.com/17829319/105472860-52dc0c00-5c94-11eb-8588-caea8455d6d1.png)

It is not a deal for me though.

**Comment by dvdhrm** [comment]
> @dvdhrm thank you, the bug is finally fixed! There's no waiting for timeout anymore, error is returned instantly as the service fails. There's no need to run the service manually to restore it functionality anymore, it restores automatically.

Thanks for confirming and for replying so fast! Sorry for missing so much of it.. I should have tested transient units and the user bus from the beginning.

> The only difference I noticed is that failed transient units aren't being removed:

Yeah, that is a systemd thing. They are cleared with `systemctl reset-failed` I think, but unsure about that. I mean, it is up to systemd what to do with this information. If that becomes an issue ever, we will have to work with Lennart on a fix (like timeing out stale units).

**Comment by benzea** [comment]
Could you add `CollectMode=inactive-or-failed` to the transient unit? It seems reasonable to me to do so, as I would expect people to look into the journal if something goes wrong with dbus activation.

**Comment by dvdhrm** [comment]
I wasn't aware this already existed. I now opened a PR that implements this. I will give this a try and then merge it for the next release.

**Comment by ilya-fedin** [comment]
#252 works perfectly for me. No activation problems, no failed units in `systemctl --user --type=service`

**Comment by dvdhrm** [comment]
> #252 works perfectly for me. No activation problems, no failed units in `systemctl --user --type=service`

Thanks for confirming! Works for me as well. I will see whether I can prep another release this or next week.
