### ISSUE TITLE
unable to filter messages

### ISSUE THREAD

**Issue by duhovasur** [bus1/dbus-broker#210]
The following command worked for me in Fedora 28, but since upgrading to Fedora 30, it doesn't show applicable dbus messages:
`dbus-monitor --session "type='method_call',interface='org.freedesktop.Notifications',member='Notify'"`
> dbus-monitor: unable to enable new-style monitoring: org.freedesktop.DBus.Error.MatchRuleInvalid: "Invalid match rule". Falling back to eavesdropping.
signal time=1563470082.399756 sender=org.freedesktop.DBus -> destination=:1.166595 serial=4294967295 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.166595"

However, running without the filter does catch the message I'm looking for (along with a zillion others):
`dbus-monitor --session`

> [...]
method call time=1563468713.173238 sender=:1.164239 -> destination=:1.164091 serial=14 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "mate-screensaver-dialog"
   uint32 0
   string ""
   string "12:51:53 P.M."
   string "testtest"
   array [
   ]
   array [
   ]
   int32 0
[...]

What's going wrong? The format of my filter matches the example in the man page...?

This issue was originally reported against dbus: https://gitlab.freedesktop.org/dbus/dbus/issues/273

Simon McVittie has indicated that it appears this is an issue with dbus-broker):
> Please report this as a bug in dbus-broker. It looks as though you are specifying a valid match rule on the dbus-monitor command-line, but dbus-broker is diagnosing it as invalid.

**Comment by keszybz** [comment]
Any progress here?

**Comment by dvdhrm** [comment]
Oh dear. So `dbus-monitor` **always unconditionally** prepends `eavesdrop=true` to all match-rules you install. Since eavesdropping is deprecated upstream, dbus-broker never implemented it and refuses any eavesdrop-rules (since the bus policy would deny them anyway).

Now there is no real reason for `dbus-monitor` to do that, actually. But what can we do... I will make `BecomeMonitor()` in `dbus-broker` allow `eavesdrop=` filters so we are compatible here. Working on a patch...

As a workaround, you can always switch to `busctl monitor`, which does not have this behavior.

**Comment by dvdhrm** [comment]
I pushed a PR to fix this. See #221 for details. Will prep a release next week.

**Comment by dvdhrm** [comment]
The release is out. This will hopefully hit Fedora-rawhide by the end of this week.

I just verified your initial command-line works, hence I am closing this as resolved. Thanks a lot for the report, and sorry for me being not around for a few months.

**Comment by pkzc** [comment]
> The release is out. This will hopefully hit Fedora-rawhide by the end of this week.
> 
> I just verified your initial command-line works, hence I am closing this as resolved. Thanks a lot for the report, and sorry for me being not around for a few months.

Looks like it has stalled.
