### ISSUE TITLE
Could not run dbus broker

### ISSUE THREAD

**Issue by ya1gaurav** [bus1/dbus-broker#215]
I am trying to run dbus broker, but it fails every time.
P.N -> dbus daemon works fine. But after "systemctl enable dbus-broker.service", dbus broker cannot be launched.

1. As a service (replacement of dbus daemon)
dbus-broker.service - D-Bus System Message Bus
   Loaded: loaded (/usr/lib/systemd/system/dbus-broker.service; enabled; vendor
preset: enabled)
   Active: failed (Result: start-limit-hit) since ...
     Docs: man:dbus-broker-launch(1)
  Process: *** ExecStart=/usr/bin/dbus-broker-launch --scope system --audit
(code=exited, status=1/FAILURE)

2. Using dbus-broker-launch binary:
No listener socket inherited

3. Using dbus-broker binary:
dbus-broker: controller file-descriptor not a socket -- '3'

4. I am using dbus-broker Release 21, Kernel 4.1.10, Systemd - 231

**Comment by dvdhrm** [comment]
What distribution are you on? Can you please list the error-logs when you try starting it as a service?

**Comment by dvdhrm** [comment]
Closing this due to lack of information. Please feel free to re-open if that problem persists.
