### ISSUE TITLE
dbus-broker performance

### ISSUE THREAD

**Issue by slowmathematician** [bus1/dbus-broker#218]
Measurements were made on JetsonTX2 with Ubuntu 18.04 LTS.
The release build of dbus-broker was used.
Here is an example of a simple request:
- Destination - org.freedesktop.NetworkManager;
- Object - /org/freedesktop/NetworkManager/Devices/1;
- Method - org.freedesktop.DBus.Properties.Get(org.freedesktop.NetworkManager.Device, Ip4Config).

The execution time of a synchronous request:
- standard dbus ~965 us;
- dbus-broker ~835 us.

This is all the advantage that dbus-broker can provide ~15% ?

**Comment by dvdhrm** [comment]
> This is all the advantage that dbus-broker can provide ~15%?

If you have questions about the advantages of dbus-broker, I recommend the introduction we wrote for its initial release:

    https://dvdhrm.github.io/rethinking-the-dbus-message-bus/

Feel free to ask more detailed questions, but currently I am not sure what information you are looking for.

**Comment by dvdhrm** [comment]
Closing this for the reasons mentioned above. If someone wants more detailed answers on dbus-broker performance, please feel free to ask.
