### ISSUE TITLE
hypen character is not escaped in systemd service name

### ISSUE THREAD

**Issue by davidedmundson** [bus1/dbus-broker#230]
"-" is a perfectly valid character for a DBus name but it has a special meaning inside systemd.

```
[D-BUS Service]
Name=net.dave.foo-bar
Exec=/bin/someapp 
```

Registers dbus-:1.2-net.dave.foo-bar@1.service 

It should be 

dbus-:1.2-net.dave.foo\x2dbar@1.service 

relevant line is  service.c:327:

        r = asprintf(&unit, "dbus-%s-%s@%"PRIu64".service", unique_name, service->name, service->instance++);

**Comment by dvdhrm** [comment]
I created a PR #231 that should fix this. Thanks a lot for the report!

**Comment by davidedmundson** [comment]
>Thanks a lot for the report!

No Problem. 

It's pretty minor for now, but FYI the reason I was looking was because I'm investigating slowly getting more parts to follow: https://systemd.io/DESKTOP_ENVIRONMENTS/ where the cgroup name will start carrying semantic value.

**Comment by dvdhrm** [comment]
This is fixed and merged. I think I will quite likely prep a release this week, so this should hit distros pretty soon. Again, thanks a lot!
