### ISSUE TITLE
Is it possible to use Dbus-broker in Chroots which run in A top of Android kernel by using Termux and Proot?

### ISSUE THREAD

**Issue by JanuszChmiel** [bus1/dbus-broker#233]
May be, that you will not believe Me, but it is really possible to use standard Dbus and other apps with Termux thanks to Proot module and thnks to some chrooted distribution such as ArchLinux. But when I have tried to install dbus-broker in ArchLinux aarch64 I have got series of errors related to some C source files of Dbus-broker. Some error has contained access denied or permission denied. So Does dbus-broker call some Linux kernel functions and procedures, which are not The part of Android kernel for Android 8 and newer? So it doesnt make sense to try Dbus-broker in The conjunction with Android? Dbus normal Dbus without Dbus-broker works.
And I have last question.

It is necessary to preconfigure normal dDbus configuration files so it will function properly with dbus-broker? Why I Am giving you this question.
Because even nomral Dbus in Fedora arch64 can not work without dbus-broker while using it with Termux, Android and Proot. So I Am thinkink, if Redhat did not preconfigured some specific configuration files or even Dbus source code to be compatible with dbus-broker in future, so it can not work in chroots even if dbus-broker is not installed.
Thank you very much for yours answers. You are elite C programmers and I helieve that you will give Me qualified answer.
Thank youv ery much for yours help.
With kindness regards.
Janusz Chmiel

**Comment by dvdhrm** [comment]
I recommend staying with `dbus-daemon` in your scenario. It will be supported in Fedora in the future, so it should work fine in situations like you describe.

dbus-broker-launch requires systemd. Currently, there is no other launcher than `dbus-broker-launch`, so there is no viable way to run dbus-broker without systemd. If you have systemd available in your setup, then dbus-broker should work just fine. If you don't, then, as I said, I recommend staying with dbus-daemon.

Lastly, dbus-daemon and dbus-broker are fully compatible. No separate configuration, nor any adjustments are needed.

**Comment by JanuszChmiel** [comment]
Dear Mr Rheinsberg,
Thank you very much for yours professional and qualified answer. Dbus-daemon
is making Me very big joy. I can use even Orca screen reader, Mate desktop
environment in chroot thanks to it.
Dbus-broker can not be used in Arch in Chroot, because Systemd do not work
in Chroot environment. I have even bigger issue. There is no reliable shared
memory emulation native .so library for Android, which will not cause system
instability. Sure. There are some attempts, but making shared memory
emulation if it is .so library which is not The part of Android kernel is
not easy. If app calls many shared memory functions at The same time, it
crashes. I had to combine non shared memory approach when using Xvnc server.
My most painfull adventure has to find reliable VNC client for Android. Orca
screen reader need precise hodkeys support. Some VNC clients did not
detected Capslock, some did not correctly detected Shift if is it hold or
no.

**Comment by dvdhrm** [comment]
I am marking this as resolved. If there are questions left, feel free to open new bug-reports. Thanks!
