### ISSUE TITLE
Ignoring duplicate name 'org.freedesktop.FileManager1'

### ISSUE THREAD

**Issue by tripLr** [bus1/dbus-broker#242]
continuing log issue
is this a dbus broker issue, or a problem with file manager ?
fedora 32

log follows 

dbus-broker-launch
Ignoring duplicate name 'org.freedesktop.FileManager1' in service file '/usr/share/dbus-1/services/org.mate.freedesktop.FileManager1.service'
--
CODE_FILE | ../src/launch/launcher.c
CODE_FUNC | launcher_load_service_file
CODE_LINE | 716
DBUS_BROKER_LAUNCH_SERVICE_NAME | org.freedesktop.FileManager1
DBUS_BROKER_LAUNCH_SERVICE_PATH | /usr/share/dbus-1/services/org.mate.freedesktop.FileManager1.service
DBUS_BROKER_LOG_DROPPED | 0
ERRNO | 0
MESSAGE_ID | 24dc708d9e6a4226a3efe2033bb744de
PRIORITY | 3
SYSLOG_FACILITY | 3
SYSLOG_IDENTIFIER | dbus-broker-launch
_AUDIT_LOGINUID | 1006
_AUDIT_SESSION | 20
_BOOT_ID | 9dc0c75423904b9ba783dd23bb796f87
_CAP_EFFECTIVE | 0
_CMDLINE | /usr/bin/dbus-broker-launch --scope user
_COMM | dbus-broker-lau
_EXE | /usr/bin/dbus-broker-launch
_GID | 1006
_HOSTNAME | triplr-server.localdomain
_MACHINE_ID | c4604b3a710643308d1e496316461694
_PID | 1336885
_SELINUX_CONTEXT | unconfined_u:unconfined_r:unconfined_dbusd_t:s0-s0:c0.c1023
_SOURCE_REALTIME_TIMESTAMP | 1601129710688699
_SYSTEMD_CGROUP | /user.slice/user-1006.slice/user@1006.service/dbus-broker.service
_SYSTEMD_INVOCATION_ID | 4a4531b0201c42ac81248313888c3c8e
_SYSTEMD_OWNER_UID | 1006
_SYSTEMD_SLICE | user-1006.slice
_SYSTEMD_UNIT | user@1006.service
_SYSTEMD_USER_SLICE | -.slice
_SYSTEMD_USER_UNIT | dbus-broker.service
_TRANSPORT | journal
_UID | 1006
__CURSOR | s=def0e507329e47438bff6d4b43de62bf;i=a484c;b=9dc0c75423904b9ba783dd23bb796f87;m=1763e14d78;t=5b0380fa51dea;x=9ab54c202ac8a234
__MONOTONIC_TIMESTAMP | 100459957624
__REALTIME_TIMESTAMP | 1601129710689770

**Comment by dvdhrm** [comment]
It means you have 2 dbus-service-files that provide the name `org.freedesktop.FileManager1`. This is not an allowed configuration.

**Comment by dvdhrm** [comment]
Closing this, as this is the expected behavior and the report has been stale for 24 days. If there are open questions left, please re-open this issue!
Thanks!
