### ISSUE TITLE
[wiki] fix command enabling user dbus-broker.service globally

### ISSUE THREAD

**Issue by Vincent43** [bus1/dbus-broker#25]
The command proposed in wiki is wrong:
`systemctl --global --user enable dbus-broker.service`

it works same as below, which enable user srvice locally.
`systemctl --user enable dbus-broker.service`

The correct command should be:
`systemctl --global enable dbus-broker.service`

https://www.freedesktop.org/software/systemd/man/systemctl.html

> --global
> 
>     When used with enable and disable, operate on the global user configuration directory, thus enabling or disabling a unit file globally for all future logins of all users.

**Comment by dvdhrm** [comment]
Oh dear... thanks a lot for reporting this. Fixed in the wiki, and the external sources should be refreshed soon as well!

Thanks a lot!
