### ISSUE TITLE
Duplicated expressions in policy.c

### ISSUE THREAD

**Issue by qarmin** [bus1/dbus-broker#267]
https://github.com/bus1/dbus-broker/blob/92142f321fc80c76ab1cc973ce2defa1039cac4a/src/launch/policy.c#L283-L284

https://github.com/bus1/dbus-broker/blob/92142f321fc80c76ab1cc973ce2defa1039cac4a/src/launch/policy.c#L348-L349

**Comment by dvdhrm** [comment]
Thanks! Fixes in 44d9d6ff303608488c2384a7679dbe70eac59995.
