### ISSUE TITLE
remove dependency on libsystemd?

### ISSUE THREAD

**Issue by pheonix9001** [bus1/dbus-broker#270]
at the moment, libsystemd is a dependency for `dbus-broker-launch`. and second of all in systems without systemd, such as artix linux, the `dbus-broker` package does not contain the `dbus-broker-launch` binary.

this issue is to remove dbus-broker-launch's dependency on libsystemd, or at least make it optional.

also if its not possible to remove its dependency on libsystemd, please suggest me a way to run dbus-broker in my s6 based system.

**Comment by teg** [comment]
`dbus-broker-launch` is the integration point between `dbus-broker` and a `systemd`-based system, so removing the dependency does not make sense.

What you could do, is to reimplement `dbus-broker-launch` for your target system. The `dbus-broker` API you need to implement is documented in the man pages, and you could look at `dbus-broker-launch` for inspiration.
