### ISSUE TITLE
activation of a masked unit results in long timeout

### ISSUE THREAD

**Issue by michich** [bus1/dbus-broker#28]
Description:
After I switched to dbus-broker, logging in to Gnome Shell takes a long time (tens of seconds), and so does starting any application. I traced the problem to activation of masked units. Instead of failing immediately, such activation requests time out.

Steps to reproduce:
systemctl --user mask --now at-spi-dbus-bus.service
time busctl --user get-property org.a11y.Bus /org/a11y/bus org.a11y.Status ScreenReaderEnabled

Actual result:
Connection timed out
real    0m25.032s

Expected result (actual result when using dbus-daemon):
Unit at-spi-dbus-bus.service is masked.
real    0m0.005s

Additional information:
dbus-broker-launch sends the activation request signal ("org.freedesktop.systemd1.Activator", "ActivationRequest") to systemd, but it implements no handling of systemd's signal about the activation failure ("org.freedesktop.systemd1.Activator", "ActivationFailure").

**Comment by teg** [comment]
Thanks for the report, and your analysis is correct, the handling of ActivationFailure is indeed missing.

**Comment by teg** [comment]
This should now be fixed in git. Closing.
