### ISSUE TITLE
Tarball signatures

### ISSUE THREAD

**Issue by heftig** [bus1/dbus-broker#298]
Please provide detached GnuPG signatures for your tarballs instead of (or in addition to) mere sha256sums.

The latter only provides integrity protection, not authentication. Consumers of your releases might not be competent enough to audit the code to the point its authenticity no longer matters.

**Comment by dvdhrm** [comment]
I only signed the tags so far, but with the rebuilt subprojects the tarballs might become more important. I uploaded a signature and amended the release-steps. Thanks for the heads-up!

**Comment by bluca** [comment]
Can you make the public key that does the tarball signature available (yes it can be fetched via the various keyservers, but nowadays those are mostly broken and to be avoided) please?

**Comment by bluca** [comment]
armored ascii format in SECURITY.md would be fine for example, so that it also shows up in the security tab

**Comment by heftig** [comment]
There's a public key at https://github.com/dvdhrm.gpg

**Comment by bluca** [comment]
Yes, but what I mean is that it should be explicitly documented as "this is the public key for releases"

**Comment by dvdhrm** [comment]
I added this information to our wiki front-page: https://github.com/bus1/dbus-broker/wiki#releases
