### ISSUE TITLE
Why is Linux 4.10 needed?

### ISSUE THREAD

**Issue by floppym** [bus1/dbus-broker#30]
The README file calls out Linux kernel >= 4.10 as a requirement. Does dbus-broker use some feature that landed in 4.10?

I am currently on the 4.9 stable series, and I would prefer not to jump off it if possible.

**Comment by gregkh** [comment]
There shouldn't be any specific kernel reason to stick with 4.9, just use the latest kernel.org releases, 4.9 is really old by now, missing lots of needed features for modern systems :)

**Comment by floppym** [comment]
My system isn't exactly modern, and 4.9 works fine for me.

I will upgrade when I see some feature that interests me.

**Comment by gregkh** [comment]
A feature like dbus-broker?  :)

**Comment by floppym** [comment]
Sure, but I would like to know exactly what feature(s) it is using.

**Comment by dvdhrm** [comment]
We actually rely on features from `linux-next`, which are not in any release, yet. While older kernels will work just fine, we will be bumping the requirements to 4.14 as soon as it is released.

In particular, those two commits we rely on:

* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/net/core/sock.c?id=28b5ba2aa0f55d80adb2624564ed2b170c19519e
* https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/net/unix/af_unix.c?id=27eac47b00789522ba00501b0838026e1ecb6f05

4.10 is just a recommendation so far. Feel free to run older kernels. There will never be a silent breakage. Either you will see a big fat error in your logs, or your kernel is fine. However, using kernels without the commit mentioned above means the broker can be DoS'ed by malicious clients, resulting in the broker restarting.

**Comment by floppym** [comment]
Thanks for explaining. Most appreciated.
