### ISSUE TITLE
typos in the wiki pages

### ISSUE THREAD

**Issue by phomes** [bus1/dbus-broker#32]
I spotted a few typos in the wiki pages. It is not possible to send pull requests for those so I will attach a diff here for my fixes for the obvious cases.

In the section "Method calls" in the Reliability pages the last sentence does not make sense. Not sure what to do with that so no fix:

> If, in turn, the error from the driver cannot be delivered, this is handled, as described in the nelike any other error message, as

https://github.com/bus1/dbus-broker/wiki/Reliability#method-calls

**Comment by phomes** [comment]
[wikidiff.txt](https://github.com/bus1/dbus-broker/files/1250040/wikidiff.txt)

**Comment by dvdhrm** [comment]
All applied. Thanks a lot!

Btw., wiki is now editable by everyone. Lets see whether I will regret that ;)
