### ISSUE TITLE
memfd_create() without MFD_EXEC nor MFD_NOEXEC_SEAL

### ISSUE THREAD

**Issue by gdamjan** [bus1/dbus-broker#322]
Recent kernels complain about dbus-broker-launch using memfd_create
```
memfd_create() without MFD_EXEC nor MFD_NOEXEC_SEAL, pid=281 'dbus-broker-lau'
```

systemd recently fixed this too with this PR
https://github.com/systemd/systemd/pull/26800

Would it be fine if we copy the same code/memfd wrapper from systemd to dbus-broker?

**Comment by dvdhrm** [comment]
Thanks a lot for the hint. I tried to address the issue in #323, let me know if you think anything else is needed!

**Comment by gdamjan** [comment]
looks good to me - as far as I can understand C code :)

**Comment by dvdhrm** [comment]
Merged. Thanks a lot for the report!
