### ISSUE TITLE
dbus-broker-launch failing to start with "Invalid argument"

### ISSUE THREAD

**Issue by elynnaie** [bus1/dbus-broker#329]
This error seems very similar to #328 but slightly different, so I'm opening a new issue for it. Upon upgrading to v34 on Arch Linux, I started to receive this error which prevented dbus-broker-launch from starting and a host of other services that depend on it (like sound). Downgrading to v33 fixed the issue.

```
Dec 18 14:50:30 hera dbus-broker-launch[5883]: ERROR launcher_load_service_dir @ ../dbus-broker-34/src/launch/launcher.c +795: Invalid argument
Dec 18 14:50:30 hera dbus-broker-launch[5883]:       launcher_load_standard_session_services @ ../dbus-broker-34/src/launch/launcher.c +918
Dec 18 14:50:30 hera dbus-broker-launch[5883]:       launcher_load_services @ ../dbus-broker-34/src/launch/launcher.c +974
Dec 18 14:50:30 hera dbus-broker-launch[5883]:       launcher_run @ ../dbus-broker-34/src/launch/launcher.c +1343
Dec 18 14:50:30 hera dbus-broker-launch[5883]:       run @ ../dbus-broker-34/src/launch/main.c +152
Dec 18 14:50:30 hera dbus-broker-launch[5883]:       main @ ../dbus-broker-34/src/launch/main.c +178
Dec 18 14:50:30 hera dbus-broker-launch[5883]: Exiting due to fatal error: -22
```

This error is printed out in the midst of a bunch of other `Invalid service file` errors, which are still present even after downgrading.

**Comment by dvdhrm** [comment]
I am quite certain this is the same problem as #328, so I am going to close this. I have pushed a fix to `main` (6aca911cd44f850cb1dce0b2c25e38c0ef49ee3a) and will release v35 shortly.

Thanks a lot for the report!
