### ISSUE TITLE
Wiki page minor correction

### ISSUE THREAD

**Issue by b02860de585071a2** [bus1/dbus-broker#332]
Good morning!

While reading over the wiki prior to [dbus-broker being implemented into Arch Linux](https://archlinux.org/news/making-dbus-broker-our-default-d-bus-daemon/), I noticed a minor spelling error on the "Deviations" page. 

As PRs cannot be opened for wikis, I've cloned it into https://github.com/b02860de585071a2/dbus-broker-wiki with this change included (see https://github.com/b02860de585071a2/dbus-broker-wiki/commit/aa3f12bb7c310ade831ab1d226a921584234af27). 

Is it possible for this to be merged in?

**Comment by dvdhrm** [comment]
Hi! I fixed the spelling. Thanks a lot! You should also be able to edit the wiki yourself now.

**Comment by b02860de585071a2** [comment]
Amazing, thank you!
