### ISSUE TITLE
Error when enabling the service on Arch Linux

### ISSUE THREAD

**Issue by mozo78** [bus1/dbus-broker#334]
Hello, I have an error when I enable the service:
https://pastebin.com/ZFBMvKmy

I don't know if this is expexted but it doesn't seem right for me.

**Comment by mozo78** [comment]
Thank you!
If I understand correctly, just installing dbus-broker is enough?

**Comment by dvdhrm** [comment]
Yes.

**Comment by mozo78** [comment]
Thank you!
