### ISSUE TITLE
seamless takeover from dbus-daemon

### ISSUE THREAD

**Issue by davide125** [bus1/dbus-broker#36]
The documentation mentions that to switch from dbus-daemon to dbus-broker a reboot is required. For systems where rebooting is expensive and/or impractical, it would be useful to have the option to effect a seamless transition where dbus-broker takes over from dbus-daemon on a live system.

**Comment by dvdhrm** [comment]
Heyho!

Switching from dbus-daemon to any other D-Bus implementation at runtime requires dbus-daemon to expose the bus-state in an atomic fashion. This is not the case.

Hence, to support a runtime transition, dbus-daemon would need to be patched. This requires to restart dbus-daemon, which itself requires a reboot.

So even ignoring the practicability of such a feature, I do not see a feasible way to implement this feature. Hence, I am closing this. If anyone has new input on this, please feel free to re-open. But please note that this is not an endorsement of this feature. I am merely stating that I don't even see a way to implement this.

Thanks!
