### ISSUE TITLE
Be able to set the servicedirs precedence

### ISSUE THREAD

**Issue by afiestas** [bus1/dbus-broker#362]
If I'm not mistaken the default servicedirs are always read before the user-defined servicedir which makes it impossible to override a DBus system installed service since the first found service has precedence.

My main use case is to be able to start a Plasma-git or a GNOME-git session and have it co-installed with the distribution shipped packages. Having both co-installed makes it a good fallback in case something goes terribly wrong with the development versions.

**Comment by dvdhrm** [comment]
This has been coming up several times lately. I believe there is no support for overriding configuration in the D-Bus reference implementation (which we follow). I might be wrong, but you really shouldn't provide multiple services files for the same service, and expect a specific one to have precedence, at least with the status-quo.

If there is desire for such configuration, this likely needs to be brought up in the issue tracker of the reference implementation (gitlab.freedesktop.org), and likely needs some design discussions. I am a bit hesitant to introduce these features without support by the reference-implementation.

Personally, I would very much prefer to get rid of the configuration alltogether, and instead require application managers to register services. For instance, systemd already knows about dbus-names of services and could just register them, and thus grant you all the configuration-features of its unit-files. `dbus-broker` already allows this, but would need direct integration into systemd for this specific example to work.

Anyway, I am not sold on a specific design for the future, so discussion is certainly welcome.

**Comment by afiestas** [comment]
I did not find any previous discussions; apologies if this has already been addressed.

Your comment is completely valid. I will open an issue in the reference implementation bug tracker and ask for feedback over there.

Your proposal is quite insightful, especially considering that D-Bus predates systemd, necessitating many features that are now redundant. However, I wonder if making systemd a hard requirement in 2024 is feasible. This, too, is a topic for discussion in the reference implementation.

Thanks!

**Comment by afiestas** [comment]
In the [dbus-freedesktop](https://gitlab.freedesktop.org/dbus/dbus/-/issues/507) issue @smcv gave a solution that is already working for both implementations

> ... so this can be achieved most easily by prepending items to the $XDG_DATA_DIRS in the session bus's parent (systemd --user activation environment, or display manager, or desktop environment) before the session bus is started.

He also suggested  adding a prepend_servicedir which personally I do not see necessary since prepending the install directory to XDG_DATA_DIRS does the trick.

Going to close the issue now.
