### ISSUE TITLE
Filtering signals by arguments does not work

### ISSUE THREAD

**Issue by TomasKorbar** [bus1/dbus-broker#367]
Hi, for some reason i am not able to get signal filtering by argument value to work.

### Reproducer

1. start monitoring dbus with `# dbus-monitor --system "arg3='done'"`
2. try to submit systemd job with for example `# systemctl restart polkit`
3. check found signal

### Expected result
signal time=1716466590.572778 sender=:1.0 -> destination=(null destination) serial=5066 path=/org/freedesktop/systemd1; interface=org.freedesktop.systemd1.Manager; member=JobRemoved
   uint32 4996
   object path "/org/freedesktop/systemd1/job/4996"
   string "polkit.service"
   string "done"
### Actual result
None

Context:
I am developing daemon that is listening for JobRemoved signal of systemd and i would like to receive only signal related to a service i am watching. I am using dbus-python but so far i am not able to get filtering by argument to work.
Am i missing something or is it possible that there is a bug?

Environment i am using is Fedora Rawhide.
dbus-broker-36-2

Thanks for any help.

**Comment by dvdhrm** [comment]
This looks like a bug in dbus-broker. In particular:

https://github.com/bus1/dbus-broker/blob/main/src/bus/match.c#L425

This uses `args[0]` instead of `args[i]`. Maybe @teg can have a look at well, but I think this needs to be fixed.

**Comment by teg** [comment]
Yikes, that's a bug indeed. Mea culpa!

**Comment by dvdhrm** [comment]
Fixed via #369 and #371. Thanks a lot for the report!
