### ISSUE TITLE
Error: "could not sync environment to dbus" on starting Plasma

### ISSUE THREAD

**Issue by beojan** [bus1/dbus-broker#37]
When starting Plasma with dbus-broker enabled, I get the error:
`could not sync environment to dbus`.

**Comment by dvdhrm** [comment]
Weird. Can you look into `~/.xsession-errors` and see what it says on this?

**Comment by dvdhrm** [comment]
Also, was there **anything** else in the log related to this? I fixed a bug in the `UpdateActivationEnvironment()` handling of dbus-broker. This could be the source of this bug. However, if that's the case, there must be some more verbose information in your logs about this.

If you find the time, can you retry with current -master? Especially, some version that includes this: https://github.com/bus1/dbus-broker/commit/b08cc9dab51eab5a4b10c147ecd4cbd8efc238d6

**Comment by beojan** [comment]
OK, it seems to work with master.
