### ISSUE TITLE
[packaging] don't call mesonconf separately

### ISSUE THREAD

**Issue by ignatenkobrain** [bus1/dbus-broker#49]
you can pass all parameters directly to `%meson` macro.

**Comment by dvdhrm** [comment]
Are arguments always appended to the macro? I looked at the upstream sources [1] and it does not append arguments to the meson command. But I have no insights how rpm macros work, so maybe that is just the default?

[1] https://github.com/mesonbuild/meson/blob/master/data/macros.meson

**Comment by ignatenkobrain** [comment]
@dvdhrm they are, so things like `%meson -Dfoo=true` work perfectly

**Comment by teg** [comment]
Thanks for the suggestion! I'll do this.

**Comment by teg** [comment]
This has now been fixed in master.
