### ISSUE TITLE
[packaging] Use proper selinux macro

### ISSUE THREAD

**Issue by ignatenkobrain** [bus1/dbus-broker#50]
https://fedoraproject.org/wiki/SELinux/IndependentPolicy

Mainly points about compression, Requires(post) and %post sections (using macro instead of calling binaries directly).

**Comment by teg** [comment]
Thanks for the suggestion! I'll do this.

**Comment by teg** [comment]
This has now been fixed in master.

**Comment by ignatenkobrain** [comment]
You miss proper Requires(pre), Requires(post), etc.
