### ISSUE TITLE
cant build on systems without systemd

### ISSUE THREAD

**Issue by emdete** [bus1/dbus-broker#52]
build fails with

```
Meson encountered an error in file meson.build, line 41, column 8:
Native dependency 'libsystemd' not found
```

on systems with different init procedures.

dbus-broker should not depend on systemd.

**Comment by dvdhrm** [comment]
Please read `README`:

```
        The requirements for dbus-broker are:

            Linux kernel >= 4.10
            glibc >= 2.16
            libselinux >= 2.5           (optional)

        Additionally, the compatibility launcher requires:

            dbus >= 1.10
            glib >= 2.50
            systemd >= 230
            expat >= 2.2

        At build-time, the following software is required:

            meson >= 0.41
            pkg-config >= 0.29
```

The dbus-broker project does not require systemd, However, if you want compatibility to dbus-daemon, we provide a compatibility launcher, and this launcher requires systemd.

To disable the launcher, you need to pass `-Dlauncher=no` to meson. However, you will not be able to replace dbus-daemon without further effort then.

**Comment by emdete** [comment]
yes, i read that note. i read as well that no config is needed (i assumed "possible") for the commands so i was lost on how to switch systemd off. thank's for explaining!
