### ISSUE TITLE
[RFC] Workarounds for at_console=

### ISSUE THREAD

**Issue by dvdhrm** [bus1/dbus-broker#56]
So `at_console=` is deprecated upstream, and I don't see us implementing it. We decided against it in the past [[1]](https://github.com/bus1/dbus-broker/wiki/Deviations) and I am unaware of a solution to the problems described.

In short: Implementing it requires running a custom hook on *EVERY* message transaction. This is a no-go for dbus-broker.

Now, while ignoring it works mostly fine, there still remain users of it. Namely, BlueZ, ConnMan, OFono, and more [[2]](https://lintian.debian.org/tags/dbus-policy-at-console.html). All of them are already on the debian-lintian bug-list, but they remain unfixed until today. While we can commit to fixing those, I'd rather first consider possible workarounds. Before doing so, lets summarize how at_console works:

The at_console= feature adds two mutually exclusive policy contexts. Depending whether a connection is considered `at the console`, the correct context is picked and pinned with that connection. At Hello(), dbus-daemon(1) invokes one of several callbacks to determine whether a connection is at the console. If systemd is used, it resolves to `sd_uid_get_seats()` returning at least one seat. This means, if the uid of the connection is logged in on at least one physical seat **at the time of Hello()**, it is considered `at the console`.

Possible workarounds in the comments. Lets keep this issue open to track this.

[1] https://github.com/bus1/dbus-broker/wiki/Deviations
[2] https://lintian.debian.org/tags/dbus-policy-at-console.html

**Comment by dvdhrm** [comment]
Solution 1:

Change `at_console=true` to `group=users`.

This means, every connection that is part of the `users` group will be considered `at-console`. Strictly speaking it means the connection is considered both `at-console` and `no-console`, but the `at_console=false` list is usually empty, so we should be fine. We could, however, simply negate all the rules in `no-console` and append them to `at-console`, to get the desired effect.

Problem: While systemd creates the `users` group by default, there does not seem to be a distribution making use of that feature. We thus would require distributions to add local users to that group.

**Comment by dvdhrm** [comment]
Solution 2:

Make use of `pkg-config --variable systemuidmax systemd` and treat any uid higher than that as `at-console`.

This should have the effect of treating all users that can login on a system as `at-console`. While not perfect, it should serve as suitable workaround.

Problem: I don't see how to implement this in the launcher. While we can query the max-uid, I don't think the current policy-model of the broker can implement this. I think we would need two more policy-arrays, `at-console` and `no-console` and pass the threshold-uid as separate argument.

**Comment by dvdhrm** [comment]
Update on Solution 1:

We could add a pam-module installed alongside dbus-broker. This module hooks into pam_open_session(3) calls `sd_uid_get_seats()` and adds the logged in user to the group `users` (or `dbus-users`, ...). We can then reliable check group-membership in dbus-daemon(1) via `SO_PEERGROUPS`.

This would get pretty close to the semantics of dbus-daemon(1). That is, we would check seat-membership at login-time rather than Hello() time. However, given that systemd modifies seat-membership exclusively at login-time, this gets preeeetty close. The only difference is, if you connect to dbus-daemon from a non-seat session, but you have another *newer* session that you created *after* you logged in but before you call Hello(), and that session is actually on a seat. I don't think that is a crucial difference, though.

Lastly, if we don't want to ship our own pam-module (nor create our own group), we can submit a PR to systemd and make pam_systemd add users to group `users`, if it is a local login.

**Comment by heftig** [comment]
I'm not sure adding new semantics to the existing `users` group is a good idea. Why do you prefer it to defining a new group?

**Comment by dvdhrm** [comment]
Ah, no preference there. I am completely fine with a new group.

**Comment by smcv** [comment]
> We could add a pam-module installed alongside dbus-broker. This module hooks into pam_open_session(3) calls sd_uid_get_seats() and adds the logged in user to the group users (or dbus-users, ...). We can then reliable check group-membership in dbus-daemon(1) via SO_PEERGROUPS.

This is flawed for the reasons discussed in <https://github.com/systemd/systemd/pull/6762> (tl;dr: the same hole involving setgid executables that is why modern Linux distributions use ACLs on `/dev/snd/**` instead of adding processes to the `audio` group).

> In short: Implementing it requires running a custom hook on EVERY message transaction

That isn't actually how the dbus-daemon implementation has ever worked, but in principle it's how it *should* have worked, because justifications like "we will let active local users shut down the machine by default because they could just pull the plug anyway" break down if you are dealing with sessions that have become inactive, or leftover processes (screen sessions?) from prior sessions.

**Comment by dvdhrm** [comment]
This is now implemented in -master. The wiki is updated as well (https://github.com/bus1/dbus-broker/wiki/Deviations).

I will close this now. If there are issues left with the implementation, please re-open or file separately.

**Comment by michich** [comment]
@dvdhrm Does this implementation treat processes of services with systemd's DynamicUser=yes (allocated from UID range 61184...65519) as at_console=yes?

**Comment by teg** [comment]
@michich no, it does not. Maybe best to open a new issue if you believe that to be wrong (my understanding is that it is not, but maybe I am missing something).

**Comment by teg** [comment]
@michich, sorry, that was wrong. We do indeed consider all uids above system uid max to be at console. I think we should consider excepting the dynamic uids.

**Comment by mbiebl** [comment]
Given that the list of packages still using ```at_console=true``` is really short, I would not have applied this workaround as I find those new semantics defined by dbus-broker weird.
I mean, the only real blocker afaics is bluez, right? Has there been any attempt to get bluez updated to use polkit?  And if so, where can I read more about it.

**Comment by teg** [comment]
There have been several pushes over the years to deprecate it. I haven't read any bluez-specific discussion, but my understanding was that the maintainers of bluez (and oFono ++) were opposed to polkit, but that is admittedly hearsay.

For reference, this seems to be a pretty good list of packages still using at_console: https://lintian.debian.org/tags/dbus-policy-at-console.html

I'd be happy if we could drop this completely of course, I think the logic we have is a tolerable compromise, but not needing it would of course be better.
