### ISSUE TITLE
org.freedesktop.DBus.ReloadConfig missing

### ISSUE THREAD

**Issue by mbiebl** [bus1/dbus-broker#57]
dbus-daemon provides a ReloadConfig method. With dbus-broker I get:
```
# dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
Error org.freedesktop.DBus.Error.UnknownMethod: Invalid method call
```

Would it make sense to provide compatibility with the reference implementation in that regard?

**Comment by dvdhrm** [comment]
Yeah, this is [planned](https://github.com/bus1/dbus-broker/wiki/TODO). I hope the next release will support reloading.

**Comment by mbiebl** [comment]
Hi, is the implementation in ffbe382 imcomplete or can this issue be closed now?

**Comment by teg** [comment]
This has now been implemented. Closing.
