### ISSUE TITLE
dbus-broker falls back to nss with 4.13 kernel

### ISSUE THREAD

**Issue by Mdyrl7777777** [bus1/dbus-broker#65]
I'm using latest stable kernel 4.13.4 which have [SO_PEERGROUPS]( https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/?h=v4.13.4&id=28b5ba2aa0f55d80adb2624564ed2b170c19519e) support but dbus-broker still warns about it:
`dbus-broker-launch: Falling back to resolving auxillary groups using nss, this is racy and may cause deadlocks. Update to a kernel with SO_PEERGROUPS support.`

Is there specific config option need to be enabled in kernel or is this false warning?

**Comment by Keruspe** [comment]
This is a build-time check, not a runtime one, so you need linux-headers >= 4.13 when building dbus-broker to effectively use the SO_PEERGROUPS stuff.

**Comment by Mdyrl7777777** [comment]
I didn't know that linux-headers is build-time dependency. I think it isn't listed as dependency in any distro that have dbus-broker packages https://github.com/bus1/dbus-broker/wiki#available-packages

**Comment by Mdyrl7777777** [comment]
Sorry, maybe I misunderstand this. In Archlinux there are two headers packages:
https://www.archlinux.org/packages/core/any/linux-api-headers/ for userspace
https://www.archlinux.org/packages/core/x86_64/linux-headers/ for kernel modules
The former is currently at 4.12.7 version. I guess that's the reason why SO_PEERGROUPS isn't supported, right?

**Comment by Keruspe** [comment]
Whichever provides `asm-generic/socket.h` needs to be at least version 4.13

**Comment by dvdhrm** [comment]
It's `linux-api-headers` on arch-linux. Unfortunately, they haven't updated it to 4.13, yet.

**Comment by Mdyrl7777777** [comment]
Updating `linux-api-headers` to 4.13 solved this. Thx for help.
