### ISSUE TITLE
user activated service not being activated without SystemdService=

### ISSUE THREAD

**Issue by doverride** [bus1/dbus-broker#70]
In the wiki is states that direct activation is no longer support and that in the event a activated service cannot be started via a systemd unit, that dbus-broker will start it with a transient unit.

However, I have such a scenario: dunst in the past was activated directly by dbus --session, however it looks like dbus-broker now just ignores /usr/share/dbus-1/services/org.knopwob.dunst.service (ie. busctl --user does not list this as activateable). I have no indication that my dbus-broker user instance is trying to create/start a transient unit either

To reproduce:

install dunst & make sure you have no other notification daemon
use notify-send to trigger activation
also confirm that busctl --user doesnt list org.knopwob.dunst.service as activate-able

**Comment by teg** [comment]
Thanks for the report. We currently don't pick up new service files at run-time (tough there is a pending PR to fix this), do you still see this problem after a reboot?

**Comment by doverride** [comment]
I think that might be a misunderstanding let me try and explain this a little bit more.

DBUS activated services are started via systemd, either via a systemd service unit, or if that is not available dbus-broker will run the dbus activated service with a transient unit.

This applies to both dbus system, as well as dbus user activated services.

I have a dbus user activated service called "dunst", this service is supposed to be dbus activated as per its /usr/share/dbus-1/services config (it has Exec=/pathto/dunst. However dunst has no accompanying systemd service unit.

That would then mean, if i understand correctly, that my dbus-broker user instance would start it with a transient unit instead. This does not happen and dbus-broker ignores the dunst dbus service config altogether.

Rebooting does not help if its a transient and/or runtime unit, since runtime units are on a tmpfs (either in /run for system or /run/user for user) So the runtime unit wouldnt survive a reboot.

**Comment by doverride** [comment]
Yes, i still see this after reboots

**Comment by doverride** [comment]
I am going to close this for now, until i can find a better way to produce this. There seems to be a conflict with awesome and dunst both claiming the same name on the bus or something
