### ISSUE TITLE
managed to crash dbus-broker

### ISSUE THREAD

**Issue by doverride** [bus1/dbus-broker#71]
```
Oct 19 12:07:13 julius dbus-broker-launch[1109]: Caught SIGCHLD of broker
Oct 19 12:07:13 julius systemd[1]: dbus-broker.service: Failed with result 'exit-code'.
Oct 19 12:07:13 julius polkitd[1118]: Lost the name org.freedesktop.PolicyKit1 - exiting
Oct 19 12:07:13 julius dbus-broker-launch[1109]: Exiting due to fatal error: -13
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       main @ ../src/broker/main.c +268
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       run @ ../src/broker/main.c +244
Oct 19 12:07:13 julius systemd[1]: dbus-broker.service: Main process exited, code=exited, status=1/FAILURE
Oct 19 12:07:13 julius bluetoothd[1115]: Disconnected from D-Bus. Exiting.
Oct 19 12:07:13 julius audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=sys.id:sys.role:systemd.system.subj:s0 msg='unit=dbus-broker comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Oct 19 12:07:13 julius avahi-daemon[1119]: avahi-daemon 0.7 exiting.
Oct 19 12:07:13 julius avahi-daemon[1119]: Leaving mDNS multicast group on interface wlp3s0.IPv4 with address 192.168.1.21.
Oct 19 12:07:13 julius avahi-daemon[1119]: Leaving mDNS multicast group on interface wlp3s0.IPv6 with address fe80::582:b79c:c415:63a4.
Oct 19 12:07:13 julius avahi-daemon[1119]: Got SIGTERM, quitting.
Oct 19 12:07:13 julius avahi-daemon[1119]: Disconnected from D-Bus, exiting.
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       broker_run @ ../src/broker/broker.c +168
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       dispatch_context_dispatch @ ../src/util/dispatch.c +345
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       peer_dispatch @ ../src/bus/peer.c +121
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       peer_dispatch_connection @ ../src/bus/peer.c +59
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       driver_dispatch @ ../src/bus/driver.c +1902
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       driver_dispatch_internal @ ../src/bus/driver.c +1808
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       driver_forward_unicast @ ../src/bus/driver.c +1763
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       peer_queue_call @ ../src/bus/peer.c +574
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       bus_log_commit_policy @ ../src/bus/bus.c +110
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       log_commit_journal @ ../src/util/log.c +504
Oct 19 12:07:13 julius dbus-broker-launch[1109]:       log_commit_journal @ ../src/util/log.c +498
Oct 19 12:07:13 julius dbus-broker-launch[1109]: ERROR log_alloc @ ../src/util/log.c +234: Permission denied
Oct 19 12:07:13 julius audit: PROCTITLE proctitle=646275732D62726F6B6572002D76002D2D6C6F670034002D2D636F6E74726F6C6C65720038
Oct 19 12:07:13 julius audit[1110]: SYSCALL arch=c000003e syscall=77 success=no exit=-13 a0=21 a1=10000000 a2=562553f59fa2 a3=23b items=0 ppid=1109 pid=1110 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="dbus-broker" exe="/usr/bin/dbus-broker" subj=sys.id:sys.role:dbus.system.subj:s0 key=(null)
Oct 19 12:07:13 julius audit[1110]: AVC avc:  denied  { write } for  pid=1110 comm="dbus-broker" name="memfd:dbus-broker-log" dev="tmpfs" ino=1331363 scontext=sys.id:sys.role:dbus.system.subj:s0 tcontext=sys.id:sys.role:fs.tmpfs.fs:s0 tclass=file permissive=0
Oct 19 12:07:13 julius audit[1110]: USER_AVC pid=1110 uid=0 auid=4294967295 ses=4294967295 subj=sys.id:sys.role:dbus.system.subj:s0 msg='avc:  denied  { send_msg } for  scontext=wheel.id:sysadm.role:wheel_cockpit_bridge_priv.subj:s0 tcontext=sys.id:sys.role:tune.daemon.subj:s0 tclass=dbus permissive=0
                                     exe="/usr/bin/dbus-broker" sauid=0 hostname=? addr=? terminal=?'
```

can anyone please tell me a little about dbus-broker-log? it seems that this log file is created on some tmpfs (likely either /tmp or /dev/shm?) Why is that?

**Comment by dvdhrm** [comment]
dbus-broker backs log-messages with a memfd. This is in case a log-message is bigger than the syslog socket allows. Note that it is highly unlikely that this happens. However, we still allocate the backing store on the first log message.

Your logs show that SELinux prevented us from truncating and mapping a memfd that we just created. This is unfortunate and requires updates to the SELinux policies. @teg, can you update them?

I am not sure why SELinux is that strict on objects we locally create...

**Comment by doverride** [comment]
My question is, does this event really have to result in dbus-broker crashing?

**Comment by doverride** [comment]
By the way, this is a personal policy configuration. Not based on refpolicy upstream selinux policy. So their policy might differ. however a quick query of their policy show that this probably would'nt be allowed in their policy either.

**Comment by doverride** [comment]
selinux policy is so strict with the end-goal to enhance integrity. Especially when it comes to processes associated with uid=0, we woudnt want to have another process that is also associated with uid=0 interfere with dbus-brokers assets like its memfd backing file.

That is why we require that this file gets a private label , so that this label can be used to govern access to the file.

However if we aren't aware that dbus-broker maintains objects on a tmpfs then we also do not allocate a label and accompanying rules with it.

**Comment by teg** [comment]
Thanks for this report, and the explanations re the SELinux policy. To the first question: does the broker have to crash in this scenario? I think so. This would mean that we try but fail to write log-messages, and if we want to support that situation gracefully we need special code to handle it and some policy to decide what to do (just drop all logs silently?). Considering that we do not actually want this to be a supported setup (this would be a bug in the SELinux policy, the broker needs the rights to do this operation), I think a hard failure is the right thing to do.

As to the bug itself: I have been trying to reproduce this in Fedora with the default SELinux policy with no success. Are you able to reproduce with the upstream policy? If so I would like to work on getting that fixed, otherwise, I think we should close this as not-a-bug.

**Comment by doverride** [comment]
In the olden day's and from a security perspective I would not have a doubt that this is the wrong thing to do, but today where DBUS is such an integral part of the system I start to have my doubts about it, but if you think it is the right thing to do then I suppose I should close this as not a bug.

I haven't tried to reproduce this with reference policy.

Closing
