### ISSUE TITLE
Small difference in behaviour from dbus-daemon

### ISSUE THREAD

**Issue by Keruspe** [bus1/dbus-broker#9]
After a day running dbus-broker as a session bus, I only noticed that little difference:

I have a gnome-shell extension which uses a GDBusProxy to start and interact with a daemon. It contains a switch representing the state of a boolean dbus property from the daemon.
If the default state from the daemon is "on", with dbus-daemon, the switch is on too, as expected, but with dbus-broker it appears off. If I explicitely re-set the dbus property to true and the PropertiesChanged signal is emitted, the switch is now on as expected.

I'm not sure if I'm clear enough, but fwiw, during the kdbus days I had exactly the same issue for a long time.

**Comment by Keruspe** [comment]
One more precision, I just did an extra test with another app that does just the same.

- if the daemon is not running yet and I start the client, the daemon gets started by the dbus activation and the switch appears off
- if I kill the client and then restart it with the daemon already running, the switch appears on

So it seems to be an issue with activation maybe?

**Comment by teg** [comment]
Thanks for the report! Pretty sure I know what this is all about. I'll take
a look.

**Comment by teg** [comment]
Could you give it another go now? At least the commit I pushed fixes something related, so we might be lucky ;)

**Comment by Keruspe** [comment]
I confirm this seems to be fixed now, thanks!
