### ISSUE TITLE
Configuration parse logic is including the top level conf file

### ISSUE THREAD

**Issue by utezduyar** [bus1/dbus-broker#96]
Configuration of "`/usr/share/dbus-1/system.conf`" is looking like this for us

```
...
...
<include>addon.conf</include>
...
...
```

dbus-broker is complaining about an unknown file @ "`/usr/share/dbus-1/system.conf/addon.conf`".

Bug found by Yang.

**Comment by umuttl** [comment]
If he can, I believe Yang is going to send a patch for it.

**Comment by dvdhrm** [comment]
Urgs, yeah, the path is obviously wrong. Should be easy to fix. I will look into this!

**Comment by umuttl** [comment]
He is going to fix it if you want to spend your time on something else

**Comment by ylse** [comment]
https://github.com/bus1/dbus-broker/pull/98

**Comment by dvdhrm** [comment]
This is fixed in master. Thanks a lot for the report!
